#!/bin/bash
this is
another
new linw
that
i need
tobe lnger
than
10 plu
or even 
more lines 
ont the comp
thanks
"(Ôo)'
total 44 -rwxr--r-- 1 root root 30 Oct 11 07:23 0-hello_world -rwxr--r-- 1 root root 28 Oct 11 07:45 1-confused_smiley -rwxr--r-- 1 root root 28 Oct 11 07:58 2-hellofile -rwxr--r-- 1 root root 39 Oct 11 08:03 3-twofiles -rwxr--r-- 1 root root 33 Oct 11 08:10 4-lastlines -rwxr--r-- 1 root root 33 Oct 11 08:13 5-firstlines -rwxr--r-- 1 root root 36 Oct 11 08:47 6-third_line -rw-r--r-- 1 root root 121 Oct 11 08:07 barbs -rw-r--r-- 1 root root 12 Oct 11 09:14 \*\'Best -rw-r--r-- 1 root root 26 Oct 11 09:20 \*\'Best \\*\'Best -rw-r--r-- 1 root root 31 Oct 11 07:05 README.md -rw-r--r-- 1 root root 0 Oct 11 08:59 School\'\*$\?\*\*\*\*\*:) -rw-r--r-- 1 root root 0 Oct 11 08:59 School\'\*$\?\*\*\*\*\*:)\
